### ISSUE TITLE
Is there a specific theme needed for it to appear correctly?

### ISSUE THREAD

**Issue by callmekatootie** [tylerxwright/vscode-line-surfer#3]
I am currently using the [Eva Theme](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme) - Dark version.

This is how your line surfer extension displays under this theme:

![image](https://user-images.githubusercontent.com/2317133/119677552-712d6080-be5c-11eb-8697-ecb24555dc6c.png)

I am guessing there's a specific theme or some constraints in using this extension...? Could not find this in the README...

**Comment by tylerxwright** [comment]
You can change the colors of the wave in the settings

![image](https://user-images.githubusercontent.com/4313815/119686586-7666bd00-be14-11eb-91be-50187535037c.png)
